### ISSUE TITLE
infinity is not working

### ISSUE THREAD

**Issue by urolithicrogue** [codehz-mcmods/infinity-fix#2]
started using this a day ago on my server and noticed that even though infinity and mending are combined the bow still uses arrows. it was on a gobber bow and i do not know if being on a server would have anything to do with it

**Comment by codehz** [comment]
It is feature :)
In readme:
```
There is only 1/6 1/3 1/2 chance of getting an arrow back when shooting
```
And this rule is copied from Minecraft: Dungeon. If it is not you want, you can use another mod like fabrication, that mod has this option
